### ISSUE TITLE
postgis/postgis:16-3.4-alpine

### ISSUE THREAD

**Issue by Mraiih** [runblaze/blaze-images#1]
Hello,

I tried to run Blaze, but had an error when the container tried to fetch the `postgis/postgis:16-3.4-alpine` image:
```
Failed to initialize container postgis/postgis:16-3.4-alpine
```

Is it a compatibility issue?

**Comment by dcvz** [comment]
Hey @Mraiih, was this on a linux runner? AMD64 or ARM64?

It could be that you were running it for the wrong architecture?
For non ARM you'd be running on `blaze/ubuntu-latest-amd64` - our default `blaze/ubuntu-22.04` is ARM64

**Comment by dcvz** [comment]
If you're running a container service, it'd be something like this (tested):

```yaml
jobs:
  test-container-service:
    runs-on: blaze/ubuntu-22.04-amd64
    services:
      postgres:
        image: postgis/postgis:16-3.4-alpine
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
          POSTGRES_DB: test_db
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Install PostgreSQL client
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client
      - name: Test PostgreSQL connection
        run: |
          echo "Checking PostgreSQL connection..."
          PGPASSWORD=postgres psql -h localhost -U postgres -d test_db -c '\l'
```
